const ICON_DATA = [
  { 
    id: 'about', 
    label: 'Zaynosaur', 
    title: 'introduction', 
    content1:'Hello, Ring',
    content2:'I made this to let you know that I have grown very fond of you. I am not entirely sure when these feelings began, and I tried to dismiss them for a while. However, they have gradually grown beyond my control.',
    content3: 'I feel deeply for you, perhaps it annoys you the same way others once did. Still, I think it is fair to be honest about how I feel. I cannot, in good conscience, not reveal myself. Please know that I hold you in genuine regard and mean no expectation nor expecting your favor by doing this. I apologize for placing you in an uncomfortable position, that was never my intention.', 
    content4:'If you wish to know greater detail, visit the other “stars.” But if you decide to stop here, thank you - truly. I am fully prepared to accept whatever consequence this honesty brings.',
    // content5:'',
    // content6:'',
    // content7:'',
    // content8:'',
    // content9:'',
    // content10:'',
    // content11:'',
    // content12:'',
    // content13:'',
    // content14:'',
    // content15:'',
    offset: -450, width: 620, height: 400 
  },
  { 
    id: 'links', 
    label: 'Zaynosaur', 
    title: 'bomb', 
    content1:'And then, wong did steel his heart, for the moment had come to unveil a most dreadful truth. With great remorse he spoke, “Forgive me, Zaynosaur, for what I am about to reveal may strike as a blow. Yet fear not, for no malice dwells within my intent, nor do I bear you any harm.”',
    content2:'*future wong here, i added this unserious part out of nervousness, i was nervous during the whole making process dubdubdubdub*',
    content3:'I was genuinely impressed when I realized you were the complete opposite of boring, to the point this impression confused me if it was just admiration for your intelligence or something that went beyond platonic. Over time, my feelings have become clear.',
    content4:"I think you’re absolutely adorable, with an uncanny sense of humor - intelligently brainsick, in the best way. Your whimsical and spontaneous nature makes you effortlessly cool. I like that you don’t talk much, but when you do, your words are always sharp and thoughtful, witty and discerning. You once said you like poems, and since this paragraph felt a bit rhythmic, I thought I’d give it a try:",
    content5:"I realized my feelings when I noticed how much I enjoy our conversations, whether serious or random. There is an unexplainable charm in the way you conduct and convey your thoughts, very clear and profound. And your opinions are subtle yet firm, rational yet kind.",
    content6:'You have such a kind heart, so kind that you always give people the benefit of the doubt, often putting others’ happiness before your own comfort. That kindness reflects in your warm and caring personality. I do not know you deeply, but I truly believe that you are lovely, evident in the fact that people around you love you for who you are; it’s no wonder your presence is always wanted. Someone once said it was ‘the glow of your presence that filled this world with beauty.’ I can’t remember who, but it feels perfectly true for you.  Although you belong to the whole world, I can sense your presence in my heart.',
    content7:'I agree with the online boys you’ve met, you really do have a nice voice. But what stands out most to me is how you can shift from a calm, monotone tone to something aggressively expressive, quite full of life. Those moments are pure gold to me. But I still wonder what makes you find your own voice unbearable. I hope you hate it less as many, including me, find it wonderful.',
    content8:'And your singing voice, it’s soft, soothing, and calming, with an ethereal, almost ghostly touch of sadness. I’m truly grateful I got to be part of your karaoke sessions; they were so good I could barely react, I was mesmerizingly bewildered by your singing. Believe me when I say it is genuinely beautiful. I’m a fan and you are my idol. And I AM NOT BIASED!',
    content9:'The more I get to know you, the more I see how effortlessly you draw people in, especially me. The feeling has been quiet but persistent. You’re very lovely, and I hate how hard it has become not to care too much.',
    content10:'It’s funny how I felt very sad when you thought I made space for everyone. I fumbled trying to explain it, maybe because it’s hard to admit directly but I don’t, I don’t, and I really don’t. That space is only for the one my heart desires.',
    content11:'My actions were more influenced by my feelings than I realized. I did things hoping they might brighten your day a bit, and I was overjoyed whenever you liked them. It’s cliché, but I teased you because I wanted your attention. I’m sorry, I know I have said foolish things and if I even went overboard; I was built like that, I am sorry. Everything I did was impulsive; my mind said no, but my heart insisted, and I’ve always been more of a heart-driven person. I never expected anything beyond friendship, yet I often found myself feeling jealous whenever other boys were involved. It wasn’t annoyance but just jealousy I couldn’t quite control.',
    content12:'You’re often on my mind. I always want to ask how your day was and wish you good night every day, but I hold back, not entirely but a little, for fear of scaring you away.',
    content13:'I truly appreciate that you’ve chosen to spend your precious time with me. I’ve looked for things we could do and games we could play, hoping for more chances to talk, because I know every bond is built on shared moments and common ground, and when those fade, the connection follows.',
    content14:'Maybe it was a sign when my Valorant stopped working properly - as if it was trying to keep me from catching feelings for you. And now here I am, writing down restless thoughts at 4AM, something I never expected to do. You once said I have bad taste - consider this my little revenge. I’m kidding, of course… though I almost confessed to you that time.',
    content15:'Pardon my enthusiasm, cheesiness, and possible cringiness - but I really really want to say that you are the fond object of my affection.',
    poem:'2, 3 little door hinges,\nI’m gonna make you cringe:\nYou’re absolutely adorable,\nyour humor uncanny, unstoppable,\nintelligently brainsick, in the best way,\nYou brighten up the dullest gray.\nYour whimsical, spontaneous flair\nmakes you so cool,beyond compare.\nYou speak so little, yet every phrase\nsharp and thoughtful, a quiet blaze.\nWitty, discerning, in every space -\nsuch unfathomable grace.',
    offset: 200, width: 880, height: 640 
  },
  { 
    id: 'work', 
    label: 'Zaynosaur', 
    title: 'bomb with impact', 
    // content1:'',
    // content2:'',
    // content3:'',
    content4:'',
    content5:'this much 👌, the gap between thumb and index',
    content6:'familiar? this is the initial purpose',
    // content8:'',
    // content9:'',
    // content10:'',
    // content11:'',
    // content12:'',
    // content13:'',
    // content14:'',
    // content15:'',
    offset: -1200, width: 1010, height: 470 
  },
  { 
    label: 'Zaynosaur', 
    title: 'my sorry', 
    content1:'I’m sorry for putting you through all of this. I know I’ve taken advantage of our friendship and your trust. I kept asking you to watch so many movies, afraid you were simply too kind to say no. Even so, I couldn’t help wanting to keep you on the call a little longer, knowing that all good things eventually come to an end. And perhaps, what I’m doing now might be what brings ours to one.',
    content2:'Whether I confess or not, I’ll have to live with these feelings until they fade on their own. I’d rather live with regret than what-ifs. And I can’t agree that you’d look better as a distant memory, your presence is one of the most precious gifts anyone could receive.',
    content3:'I know six months isn’t a long time, but everything that’s happened will be cherished for as long as I live, I mean it. Still, six months is quite a while to finish Under the Oak Tree. I’m only halfway through, thanks to my embarrassingly slow reading speed, but I really like the thought of discussing it with you, though I’m not sure if I’ll still have the chance. I haven’t watched Given yet either, but I sure will.',
    content4:'Once again, I’m fully prepared for the consequences and expect nothing in return. So, Wong would like to offer his sincerest apology, he may have overused this phrase, but he has meant it every single time.',
    content5:'wong hopes Zaynosaur soon finds someone who loves her as she’s always deserved, for as long as possible, someone who picks her every day, reads her favorite books just to talk about them, and names a star after Zaynousaur. Someone reliable for her to trust and share her thoughts without hesitation.',
    content6:'wong thinks “love you to the moon and back” is overused and overrated, so he hopes Zaynosaur finds someone who has a big enough love they could give Zaynosaur the sun.',
    content7:'If Zaynosaur makes it this far, wong is grateful and hopes this whole experience is not that bad. Hope this page is more interesting than four pages of a4 that wong has been writing for the past few days.',
    content8:'Wish Zaynosaur all the best. Stay classy, stay cool, and don’t be a fool. Just kidding, stay hydrated. Have a nice day, byeee Ring',
    content9:'',
    content10:'',
    content11:'',
    content12:'',
    content13:'',
    content14:'',
    content15:'',
    offset: -200, width: 910, height: 580 
  },
];
export default ICON_DATA;